branches:
- release-1.15
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20240729-fb7cfc68e
jobs:
- args:
  - bash
  - -c
  - |
    mkdir -p /root/.kube
    cat /opt/cluster/ci-script > connect.sh
    chmod +x connect.sh
    ./connect.sh operator-115
    kubectl get cm s390x-config-operator -n default -o jsonpath='{.data.adjustment-script}' > adjust.sh
    chmod +x adjust.sh
    ./adjust.sh
    ./test/e2e-tests.sh --run-tests
  command:
  - runner.sh
  cron: 20 12 * * *
  env:
  - name: INGRESS_CLASS
    value: kourier.ingress.networking.knative.dev
  name: s390x-e2e-tests
  requirements:
  - s390x
  types:
  - periodic
