org: knative
repo: operator
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20240729-fb7cfc68e

jobs:
  - name: s390x-e2e-tests
    cron: 20 0 * * *
    types: [periodic]
    requirements: [s390x]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        mkdir -p /root/.kube
        cat /opt/cluster/ci-script > connect.sh
        chmod +x connect.sh
        ./connect.sh operator-main
        kubectl get cm s390x-config-operator -n default -o jsonpath='{.data.adjustment-script}' > adjust.sh
        chmod +x adjust.sh
        ./adjust.sh
        ./test/e2e-tests.sh --run-tests
    env:
      - name: INGRESS_CLASS
        value: kourier.ingress.networking.knative.dev